version: '3'
services:
  images-downloader:
    build: images_downloader:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /images:/images
volumes:
  images:
    driver: local